reinfer/cli

- api/src/resources/comment.rs
- cli/src/commands/create/comments.rs
- cli/src/commands/get.rs
As these states are now distinct, technically.
> comment: rename is_reviewed -> has_annotations

- Cargo.lock
- api/Cargo.toml
- api/src/errors.rs
- api/src/resources/bucket.rs
- cli/src/commands/create/bucket.rs
- cli/tests/test_buckets.rs
Validates that a bucket name is well formed on creation.
> create bucket: validate bucket name

- Cargo.lock
- api/Cargo.toml
- cli/Cargo.toml
Closes #42 
Closes #43 
Closes #44
> deps: updates for feb 2021

- Cargo.lock
- api/Cargo.toml
- api/src/error.rs
- api/src/lib.rs
- api/src/resources/comment.rs
- cli/src/commands/create/comments.rs
- cli/tests/samples/audio.jsonl
- cli/tests/samples/phone-call-1.flac
- cli/tests/test_comments.rs
Simple support for uploading audio files associated with comments -- the stats are kind of broken as we don't include the audio file size in the upload, but much more convenient than curl.
> feature: support for uploading comments with audio

- .github/workflows/publish.yml
- README.md
- cli/publish-binaries
- scripts/check-versions
- scripts/publish-install
Tested here: https://github.com/reinfer/cli/runs/2015902856?check_suite_focus=true
> ci: publish binaries for mac

- Cargo.lock
- api/Cargo.toml
- api/src/resources/user.rs
- cli/Cargo.toml
Allows unknown global and organisation permissions
> Allow unknown permissions

- CHANGELOG.md
- api/src/resources/bucket.rs
- cli/src/commands/create/bucket.rs
- cli/tests/test_buckets.rs
Relates to https://github.com/reinfer/platform/issues/7012
> buckets: make transform tag required

- Cargo.lock
- cli/Cargo.toml
- cli/src/commands/create/dataset.rs
- cli/tests/test_datasets.rs
Adds validation to input for the Dataset name to ensure that the URL that's constructed is what the API expects.
> cli: Add validator check for Dataset name

- CHANGELOG.md
- Cargo.lock
- README.md
- api/Cargo.toml
- api/src/resources/bucket.rs
- api/src/resources/dataset.rs
- api/src/resources/email.rs
- api/src/resources/source.rs
- api/src/resources/trigger.rs
- api/src/resources/user.rs
- cli/Cargo.toml
- cli/src/commands/create/dataset.rs
Adding things I found to be missing as part of migrating Joe's gpt-data-generator tool to the official client. There will be more I'm sure!
See the changelog for a description of the changes.
Prepped to release as v0.7.0, as contains a breaking change.
> feat: implement more traits on existing structs

- api/src/lib.rs
- cli/src/commands/config.rs
- cli/src/commands/create/bucket.rs
- cli/src/commands/create/comments.rs
- cli/src/commands/create/emails.rs
- cli/src/commands/create/source.rs
- cli/src/commands/delete.rs
- cli/src/commands/get.rs
- cli/src/progress.rs
Fixes some clippy linting errors
> clippy: fix linting

- api/src/lib.rs
- api/src/resources/mod.rs
Just a quick cleanup to remove a trait abstraction and use a fixed struct.
> response: simplify error responses

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/mod.rs
- api/src/resources/project.rs
- cli/src/commands/create/mod.rs
- cli/src/commands/create/project.rs
- cli/src/commands/delete.rs
- cli/src/commands/get.rs
- cli/src/commands/update/mod.rs
- cli/src/commands/update/project.rs
- cli/src/printer.rs
- cli/tests/common.rs
- cli/tests/test_projects.rs
- cli/tests/tests.rs
This PR adds commands to manage projects via the CLI.
> projects: add crud commands

- Cargo.lock
- cli/Cargo.toml
> deps: updates for 2021-10

- cli/src/commands/create/annotations.rs
Follow up from #100 
Also print failed uid on annotation upload, not just comment.
> annotations: return id for failed comment upload

- CHANGELOG.md
- Cargo.lock
- README.md
- api/Cargo.toml
- cli/Cargo.toml
> release v0.10.0

- Cargo.lock
- api/Cargo.toml
- api/src/lib.rs
- api/src/resources/source.rs
- api/src/resources/user.rs
- cli/src/commands/create/source.rs
- cli/tests/test_sources.rs
Add `--source-type` parameter to source creation.
> api/cli: add source-type parameter to source create [RE-913]

- CHANGELOG.md
- Cargo.lock
- README.md
- api/Cargo.toml
- cli/Cargo.toml
> release v0.10.1

- CHANGELOG.md
- Cargo.lock
- api/Cargo.toml
- cli/Cargo.toml
- Fixes serialization issue where statistics expected `usize` not `f64`
> release 0.10.2

- README.md
- cli/publish-binaries
- scripts/check
- scripts/check-versions
Until the permissions issue is fixed
> revert: readd versioned links to readme

- cli/tests/test_projects.rs
~Don't merge, just seeing if this fixes the race condition~
Well, tests pass on this branch, who knows. Hopefully it helps.
> cli: sleep after creating test projects

- CHANGELOG.md
- cli/src/commands/create/trigger_exception.rs
> create: fix trigger-exception description, update changelog

- api/src/resources/source.rs
- cli/src/commands/create/source.rs
- cli/src/printer.rs
- cli/tests/test_sources.rs
[RE-1978](https://reinfer.atlassian.net/browse/RE-1978)
tested locally after building `api` from https://github.com/reinfer/platform/pull/14729
> source: support setting transform tag on creation (RE-1978)

- CHANGELOG.md
- Cargo.lock
- README.md
- api/Cargo.toml
- cli/Cargo.toml
- Display project ids when listing projects
- Add support for getting or deleting a single user
- Upgrade all dependencies to their latest released version
- Enable retry logic for uploading annotations
> release: 0.12.0

- CHANGELOG.md
- api/src/resources/source.rs
- cli/src/commands/update/source.rs
API PR: https://github.com/reinfer/platform/pull/15602
Tested against Staging
> source: support setting transform tag on update

- cli/src/commands/get/comments.rs
Attempts to enable getting predictions by timerange
> comments: enable get predictions by timerange

- CHANGELOG.md
- Cargo.lock
- README.md
- api/Cargo.toml
- cli/Cargo.toml
> release v0.12.1

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/user.rs
- cli/src/commands/create/mod.rs
- cli/src/commands/create/user.rs
Adds an option to send a welcome email when creating a user
> commands: add option to send welcome email on create user

- api/src/retry.rs
- cli/tests/test_comments.rs
To unblock publishing binaries
> chore: fix clippy errors

- CHANGELOG.md
- Cargo.lock
- README.md
- api/Cargo.toml
- cli/Cargo.toml
In preparation for publishing new release
> release v0.12.2

- CHANGELOG.md
- Cargo.lock
- api/Cargo.toml
- api/src/error.rs
- api/src/lib.rs
- cli/src/commands/create/comments.rs
- cli/src/commands/create/emails.rs
Adds an option to allow internal users to bypass billing.
> create: add option to bypass billing

- .github/workflows/publish.yml
> actions: update runner to macos-12

- CHANGELOG.md
- api/src/resources/dataset.rs
Adds recent as an order option for the query api
> api: Add recent as an order option for query api

- CHANGELOG.md
- Cargo.lock
- api/src/lib.rs
- api/src/resources/user.rs
- cli/Cargo.toml
- cli/src/commands/create/comments.rs
- cli/src/commands/create/emails.rs
- cli/src/commands/mod.rs
Adds a warning when users who have permission to bypass billing are not bypassing billing
> Add a warning for UiPath cloud users when an operation will charge ai units

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/comment.rs
- cli/tests/samples/basic.jsonl
- cli/tests/test_comments.rs
Adds markup for comments, as per: https://uipath.atlassian.net/browse/RE-418
> cli: include markup for comments

- Cargo.lock
- api/src/resources/quota.rs
- cli/Cargo.toml
- cli/src/commands/create/quota.rs
- cli/src/main.rs
- cli/src/printer.rs
- cli/src/thousands.rs
Also change quota type to u64, which is what the API actually expects (and what we store in cockroachdb).
> cli: remove num-format dependency

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/comment.rs
- api/src/resources/dataset.rs
- api/src/resources/source.rs
- cli/src/commands/get/comments.rs
Makes sure the progress bar shows the correct statistics when downloading comments
> comments: show correct statistics when downloading comments

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/documents.rs
- api/src/resources/mod.rs
Adds the `sync-raw-emails` endpoint to the api client
> api: add sync raw emails request

- CHANGELOG.md
- Cargo.lock
- README.md
- api/Cargo.toml
- cli/Cargo.toml
> release v0.17.0

- CHANGELOG.md
- Cargo.lock
- README.md
- api/Cargo.toml
- cli/Cargo.toml
> release v0.17.1

- CHANGELOG.md
- Cargo.lock
- README.md
- api/Cargo.toml
- cli/Cargo.toml
> release v0.17.2

- CHANGELOG.md
- Cargo.lock
- api/src/lib.rs
- cli/Cargo.toml
- cli/src/commands/get/comments.rs
- cli/tests/test_comments.rs
Allows you to only download specific comment predictions from a dataset by filtering on label name
> comments: Label filter on get comments

- CHANGELOG.md
- Cargo.lock
- README.md
- api/Cargo.toml
- cli/Cargo.toml
> release v0.18.0

- CHANGELOG.md
- api/src/resources/documents.rs
> api: add comment id to document

- CHANGELOG.md
- Cargo.lock
- README.md
- api/Cargo.toml
- cli/Cargo.toml
> release v0.18.1

- CHANGELOG.md
- Cargo.lock
- README.md
- api/Cargo.toml
- cli/Cargo.toml
> release v0.19.0

- CHANGELOG.md
- Cargo.lock
- README.md
- api/Cargo.toml
- cli/Cargo.toml
> release v0.21.1

- CHANGELOG.md
- Cargo.lock
- README.md
- api/Cargo.toml
- cli/Cargo.toml
> release v0.21.5

- CHANGELOG.md
- cli/src/commands/parse/emls.rs
- cli/src/commands/parse/mod.rs
- cli/src/commands/parse/msgs.rs
Resolves: https://github.com/reinfer/cli/issues/263
> fix(parse): case insensitive file name match

- CHANGELOG.md
- api/src/resources/quota.rs
- cli/src/printer.rs
> feat(quotas): show usage on get quotas

- CHANGELOG.md
- api/src/lib.rs
For long running calls like stream results
> fix(http): increase default timeout to 120s

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/comment.rs
- cli/src/commands/get/comments.rs
- cli/src/commands/mod.rs
Adds the ability to download attachment content for comments
> feat(commands): add ability to download attachment content for comments

- CHANGELOG.md
- api/src/error.rs
- api/src/lib.rs
- api/src/resources/attachments.rs
- api/src/resources/comment.rs
- api/src/resources/mod.rs
- cli/src/commands/create/annotations.rs
- cli/src/commands/create/comments.rs
- cli/src/commands/mod.rs
Adds  the ability to round upload attachment content
> feat(commands): add ability to upload attachments for comments

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/attachments.rs
- api/src/resources/audit.rs
- api/src/resources/comment.rs
- api/src/resources/documents.rs
- api/src/resources/email.rs
- cli/src/commands/create/comments.rs
- cli/src/commands/create/user.rs
- cli/src/commands/get/emails.rs
- cli/src/commands/parse/emls.rs
- cli/src/commands/parse/msgs.rs
Adds ability to get email by id and cleans up how we manage attachment metadata
> feat(commands): add get email by id

- CHANGELOG.md
- Cargo.lock
- README.md
- api/Cargo.toml
- cli/Cargo.toml
> release v0.30.0

- CHANGELOG.md
- api/src/resources/dataset.rs
- cli/src/commands/create/dataset.rs
- cli/tests/test_datasets.rs
Adds dataset flags for `create dataset`
> feat(commands): add dataset flags

- CHANGELOG.md
- api/src/resources/entity_def.rs
Round trip `_entity_def_flags`
> feat(cli): round trip entity def flags

- api/src/resources/comment.rs
- cli/src/commands/config.rs
- cli/src/config.rs
- cli/tests/test_projects.rs
Waits for user to exist in project, not just for the project to exist
> fix(tests): fix flaky project_force_delete test
