reinfer/cli

- api/src/resources/comment.rs
- api/src/resources/trigger.rs
For https://github.com/reinfer/platform/issues/8010
Makes sentiment optional in all predicted label objects (as it should not be present for sentimentless datasets at all).
> comment: make predicted label sentiment optional everywhere

- .github/workflows/publish.yml
- check
- scripts/build
- scripts/check
- scripts/publish
Also adds caching for rust dependencies, which should speed up build times.
This will definitely not work until the following secrets are populated by an admin (@mcobzarenco):
- `GCP_SA_KEY`, a GCP Service Account Key which has write access to the `gs://reinfer-public` bucket
- `CRATES_IO_TOKEN`, a crates.io token with publish permissions to the `reinfer-cli` and `reinfer-client` crates.
> ci: update github actions, add publish workflow for version tags

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/comment.rs
- cli/src/commands/create/comments.rs
- cli/src/commands/create/emails.rs
- cli/src/commands/get.rs
- cli/src/errors.rs
- cli/tests/samples/duplicates.jsonl
This PR introduces two flags:
- `--allow-duplicates` - if set, comments with duplicate IDs are permitted for upload. If not set, the file is checked for duplicate IDs before the upload start. **I made it mandatory to specify this flag if uploading from stdin.**
- `--overwrite` - if set, uses the `/sync` endpoint instead of put endpoint.
The current behaviour is equivalent to `--allow-duplicates --overwrite`, so this PR makes the CLI stricter with the intention of catch erroneous data upload earlier.
> task: Reject duplicate comment ids by default

- .github/workflows/publish.yml
- CHANGELOG.md
- Cargo.lock
- api/Cargo.toml
- cli/Cargo.toml
Version bumps plus change `publish.yml` to trigger based on Github release.
> Release v0.4.0

- CHANGELOG.md
- api/src/resources/source.rs
- cli/src/commands/create/source.rs
- cli/tests/test_sources.rs
This improves the output of `re create source source-missing-owner` from:
```
E Operation to create a source has failed
E  |- API request failed with 405 Method Not Allowed: 405 Method Not Allowed
```
to:
```
error: Invalid value for '<source-name>': Expected <owner>/<name> or a source id, got: no-owner
```
The best way to test this was via an integration test, so please merge #22 first. After then I'll rebase this PR to isolate just the relevant changes (from `89aea98`).
> task: improve invalid source name error message

- .github/workflows/rust.yml
- cli/src/commands/create/comments.rs
Workaround until clippy correctly invaliding `cargo check` cache is fixed. (See issue referred to in the comment.)
> ci: Add clippy as separate job

- CHANGELOG.md
- Cargo.lock
- api/Cargo.toml
- api/src/lib.rs
- api/src/retry.rs
- cli/src/main.rs
Add timeout handling at the `reinfer_client` level for API requests. It's disabled by default in the library config.
The CLI enables it to what I call "automatic" timeout handling, which attempts to retry all requests except for the very first. This should mean that if the first request fails with a timeout, the CLI assumes the configured endpoint is invalid and won't retry, leading to a nice quick failure.
For longer-running operations spanning multiple requests, this should lead to nice stability in the face of network connection blips.
This is what stderr looks like when the retry kicks in:
```
W error sending request for url (https://foobarwat.com/qux): operation timed out - retrying after 10s.
W error sending request for url (https://foobarwat.com/qux): operation timed out - retrying …
```
> task: Add retry on timeout for multi-request cmds

- Cargo.lock
- cli/tests/common.rs
At the moment to be "smart" the integration tests try to default the organisation to be the same as the username.
Almost always a user doesn't have an organisation which matches their username, so this often fails.
Also implicit behaviour is probably not good. These tests now require the env variable to be set explicitly.
> tests: require integration tests to be explicit about organisation

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/comment.rs
- cli/src/commands/delete.rs
- cli/tests/test_comments.rs
Adds the ability to delete comments by id in a source.
Example usage:
```bash
cargo run -- delete comments --source org1/naughty-comments plain_comment plain_comment_translated
```
Includes factoring out:
- `id_list_query` as a more generic implmentation
- `get` to reuse `get_query` (to follow the pattern of `delete_query`)
> api/cli: add 'delete comments' to delete comments by id

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/bucket.rs
- cli/src/commands/create/bucket.rs
- cli/src/commands/get.rs
- cli/tests/common.rs
- cli/tests/test_buckets.rs
- cli/tests/tests.rs
We've already been able to specify this, it was just missing.
Will soon be required, so we'll need to have it in the CLI to create buckets.
cc @Joe-Prosser if you're interested in how the cli interacts with the api
> buckets: add transform tag to create and get commands

- cli/tests/common.rs
Just in case anyone wants to choose context when running `cargo test`.
> tests: add REINER_CLI_TEST_CONTEXT env var

- api/src/error.rs
- api/src/resources/comment.rs
- api/src/resources/dataset.rs
- cli/src/commands/create/dataset.rs
Currently blocked on deploying the `api` change allowing to use the builtin names inside `inherits_from`.
We currently support the `-e` flag at dataset creation to enable specific entity kinds. However, as we are now in a world that uses `EntityDef`-s, the cli needs to be able to create these more complex objects.
One thing I had to decide was how the user would be passing these objects to the api. I opted for providing the corresponding json object, à la `curl`. Happy to go another way if someone has a better suggestion.
Example use:
```
re create dataset org/example-dataset -s org/example-source --has-sentiment false -e '{"name":"trainable_org","title":"Custom Organisation","inherits_from":["org"],"trainable":true}' -e '{"name":"non_trainable_person","title":"Basic …
```
> Allow users to specify EntityDef-s at dataset creation

- .github/workflows/rust.yml
- Cargo.lock
- cli/Cargo.toml
- cli/tests/common.rs
- cli/tests/test_buckets.rs
Replaces #49 as we only need one of the context, or the endpoint + token to be set.
> tests: require test environment to be set

- CHANGELOG.md
- Cargo.lock
- README.md
- api/Cargo.toml
- api/src/lib.rs
- cli/Cargo.toml
- cli/src/args.rs
- cli/src/commands/config.rs
- cli/src/config.rs
- cli/src/main.rs
- cli/src/utils.rs
Add support for using an HTTP proxy for all requests. The proxy configuration is saved as part of the context.
Additionally, the proxy can be overridden / specified as a one off using a global command line argument `--proxy https://proxy.example` (e.g. similar to `--endpoint` / `--token`).
E.g.
```
re get comments // uses proxy from context
re --proxy http://112.78.165.190:8080 // overwrites the proxy from the context with the given one
````
To add a proxy to a context
```
re config add -n my-context --proxy http://myproxy.example
```
NB. When modifying a context interactively, the user is not asked about changing the proxy because I had to deal with it being an `Option<Option<<>>` and couldn't reuse the stdin input util and didn't bother.
I tried it out with online free HTTP proxies. …
> api/cli: support for HTTP proxies

- api/src/lib.rs
- api/src/resources/comment.rs
- api/src/resources/source.rs
- cli/src/commands/create/comments.rs
- cli/src/commands/create/emails.rs
- cli/src/commands/delete.rs
- cli/src/commands/get.rs
- cli/src/progress.rs
- cli/tests/samples/many.jsonl
- cli/tests/test_comments.rs
- cli/tests/test_datasets.rs
- cli/tests/tests.rs
Adds a new CLI command for deleting comments in bulk in a source. 
Example usage to delete all unannotated comments in the (inclusive) range `2015-01-01T00:00:00Z` -> `2017-07-30T00:00:00Z`.
```
re delete bulk --source org/delete-me --from-timestamp 2015-01-01T00:00:00Z --to-timestamp 2017-07-30T00:00:00Z
```
By default, comments that are annotated in any dataset containing the source are NOT deleted. Note that only datasets visible to the user account making the request are considered. To delete annotated comments as well, use the `--include-annotated` flag (has to be `=true`)
```
re delete bulk --source org/delete-me --from-timestamp 2015-01-01T00:00:00Z --to-timestamp 2017-07-30T00:00:00Z --include-annotated=true
```
---
Notes:
- I called everything "annotations" / "annotated" instead …
> cli: add bulk delete command

- CHANGELOG.md
- api/src/resources/dataset.rs
- cli/src/commands/create/dataset.rs
- cli/tests/test_datasets.rs
Adds the `copy_labels_from` and `model_family` arguments for the `create/dataset` route.
> create-dataset: add label copying and model family args

- CHANGELOG.md
- Cargo.lock
- api/src/lib.rs
- api/src/resources/dataset.rs
- api/src/resources/source.rs
- cli/Cargo.toml
- cli/src/args.rs
- cli/src/commands/create/dataset.rs
- cli/src/commands/mod.rs
- cli/src/commands/update/dataset.rs
- cli/src/commands/update/mod.rs
- cli/src/commands/update/source.rs
- cli/src/main.rs
- cli/tests/test_datasets.rs
- cli/tests/test_sources.rs
Add cli and api constructs to allow updating sources and datasets.
As well as just increasing coverage of our API, we need this for `gpt-data-generator` internally.
> cli: update dataset/source

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/comment.rs
- cli/src/commands/get.rs
- cli/tests/test_comments.rs
Allows fetching a single comment by id. Added for `gpt-data-generator`, but also exposed in the cli as a useful tool for end users.
> api/cli: get comment by id

- CHANGELOG.md
- cli/src/args.rs
- cli/src/commands/create/bucket.rs
- cli/src/commands/create/dataset.rs
- cli/src/commands/create/mod.rs
- cli/src/commands/create/source.rs
- cli/src/commands/create/user.rs
- cli/src/commands/get.rs
- cli/src/commands/mod.rs
- cli/src/commands/update/dataset.rs
- cli/src/commands/update/mod.rs
- cli/src/commands/update/source.rs
- cli/src/main.rs
- cli/src/printer.rs
- cli/src/utils.rs
- cli/tests/test_buckets.rs
- cli/tests/test_datasets.rs
- cli/tests/test_sources.rs
This PR:
- refactors the collection of `print_*_table` functions into a struct, `Printer`, and trait, `DisplayTable`.
- also extends the `Iterator` trait to allow easy printing of iterables of resources
- adds printing functionality to the resources returned in the `create` and `update` subcommands
This is a breaking change. Users updating to a new version of the cli will need to update their usage. If desired, I could leave the old `-o/--output` flags in, and somehow shim them in (overriding the global output flag preference). This would make it a back-compatible change.
New sample usage:
```bash
$ re -ojson create source org1/tmp | jq
W TLS certificate verification is disabled. Do NOT use this over an insecure network.
I New source `org1/tmp` [id: 7fde97d466fcc74e] created successfully …
```
> cli: refactor data printing, print on create/update

- api/src/resources/comment.rs
This enables us to roundtrip annotation metadata once these are returned by the api.
> api: add flatten serde field to Label

- CHANGELOG.md
- api/src/resources/comment.rs
- cli/src/commands/get.rs
This PR is a hot fix to provide a way to download thread properites. These are now deserialized when dowloading comments for a dataset, `re get comments source -d dataset`. This limitation exists as only the `/labellings` API route returns thread properties.
Note, the thread properties are returned top-level as that's what the API does, e.g. 
```json
{
"comment": {
"id": "11047305213",
"uid": "530f10db824404b5.11047305213",
"thread_id": "3c3131303437333035323e",
"timestamp": "2020-01-09T16:34:45Z",
"messages": [],
"user_properties": {}
},
"thread_properties": {
"duration": 0,
"response_time": 0,
"num_messages": 19,
"thread_position": 5,
"first_sender": "cs@farfetch.com"
}
}
```
> Deserialize thread properties when using labellings route

- CHANGELOG.md
- cli/src/commands/config.rs
Simple addition that prints the token for a given context e.g.
```
$ re config get-token local
BXNAJGQQ75V3NPFYPRKE4YKUOKOYQATZWC23YDPS27K4TP7Y
```
```
$ re config get-token some-context
E No such context `some-context`.
```
This can be used in a curl command like
```
curl -XPOST                                                           \
-H"Content-type:application/json"                                 \
-H"Authorization: Bearer $(re config get-token beazley)"          \
https://beazley.reinfer.io/api/_private/users/support-tenants/add \
-d '{"email": "joe.prosser@reinfer.io"}'
```
> config: add get-token

- api/src/resources/comment.rs
When uploading annotated comments `thread_position` is not guaranteed to be returned by the API. This PR ensures that uploads do not fail when those `thread_position` is not present in the response.
> api: make thread position optional

- CHANGELOG.md
- cli/src/commands/create/comments.rs
Adds a `uid` to the error message when uploading annotations - I found this much more useful when debugging failing annotation uploads.
> comments: Return id for failed comment.

- cli/publish-binaries
Only upload a binary if it does not already exist - previously this would cause failures when retrying a previous attempt that had failed to publish all required binaries
> ci: only upload binary when it does not already exist

- api/src/resources/statistics.rs
- cli/src/commands/config.rs
- cli/src/commands/create/annotations.rs
- cli/src/commands/get.rs
We recently changed the api to return floats instead of integers in the `statistics` endpoint, which broke the deserialization logic here.
> api/cli: fix deserialization of statistics response

- api/src/lib.rs
- api/src/resources/source.rs
- cli/src/commands/create/source.rs
- cli/src/commands/delete.rs
- cli/src/main.rs
- cli/tests/test_sources.rs
This has changed in the api so changing it here for consistency and to support the source response correctly.
> api/cli: rename source type to kind

- CHANGELOG.md
- cli/src/commands/create/dataset.rs
Don't know if this is controversial, but I think if we make `--has-sentiment` optional then it should default to `false`, since that's what we want most of the time. (I think that it defaults to `true` in api v1 for purely historical reasons). Motivated by accidentally creating sentiment-enabled datasets at UBS multiple times, which was an ordeal to change.
I have no idea what I'm doing here but it seems to work!
> api/cli: default `has-sentiment` to false

- .github/workflows/rust.yml
- CHANGELOG.md
- api/src/error.rs
- api/src/lib.rs
- api/src/resources/project.rs
- api/src/resources/user.rs
- cli/src/commands/create/user.rs
- cli/tests/common.rs
- cli/tests/test_buckets.rs
- cli/tests/test_datasets.rs
- cli/tests/test_sources.rs
Not much to say -- this PR renames organisation -> project throughout the `cli` and `api` crates for consistency with new API
> api/cli: rename organisation -> project

- .github/workflows/publish.yml
Someone forgot to change the publish workflow when he changed the variable name :speak_no_evil:
> github: fix publish workflow to use projects env var

- api/src/lib.rs
- api/src/resources/comment.rs
- api/src/resources/trigger.rs
- cli/src/commands/create/mod.rs
- cli/src/commands/create/trigger_exception.rs
I needed to test trigger exceptions for my filtering refactoring, so thought I'd add to the CLI rather than working out the curl by hand.
Implemented using the :sparkles: amazing :sparkles: API docs here, as I've never touched this code before: https://developers.reinfer.io/api/reference/triggers#tag-an-exception
```log
$ re create trigger-exception --trigger org2/ee-twitter-nps/hello-integration --type "Sad Violin" --uid "64904092030935f4.2211b04b1b6391172965b57e37d5a9cb"
W TLS certificate verification is disabled. Do NOT use this over an insecure network.
I New trigger exception created successfully
```
> create: trigger-exception

- CHANGELOG.md
- Cargo.lock
- README.md
- api/Cargo.toml
- cli/Cargo.toml
v0.11.0 isn't released yet due to failing CI build. So reverting the readme(s) to point to v0.10.2 to fix broken links.
> Revert to v0.10.2 links in readmes

- api/src/resources/project.rs
- cli/src/printer.rs
Future support for showing project ids in `re get projects`.
This is not blocked on the corresponding api PR - it will work with current platform, and future versions where id is returned.
> add project id

- .github/workflows/publish.yml
By the look of it, `google-github-actions/setup-gcloud` have changed `master` to `main`, updating the config to fix this.
> github: update config file for publishing action

- api/src/resources/bucket.rs
- api/src/resources/dataset.rs
- api/src/resources/source.rs
- api/src/resources/user.rs
- cli/src/progress.rs
Clippy is failing on master, I think due to a rust update? Attempting to fix.
> Make clippy happy

- .github/workflows/rust.yml
- api/src/resources/comment.rs
This is same way as `publish.yml` is already configured.
I would like to be able to run the build Github action on master to test if it works properly there.
> Allow build github action to be triggered manually

- Cargo.lock
- api/Cargo.toml
- cli/Cargo.toml
- cli/src/commands/config.rs
- cli/src/commands/create/emails.rs
- cli/src/printer.rs
- cli/tests/common.rs
- cli/tests/test_buckets.rs
- cli/tests/test_comments.rs
- cli/tests/test_datasets.rs
- cli/tests/test_projects.rs
- cli/tests/test_sources.rs
Does two things
- Upgrade all dependencies by running `cargo upgrade` and `cargo update` -- except `indicatif` which was kept back as it needed more changes
- Fixes clippy lints from rustc 1.65.0
> api/cli: upgrade dependencies and rustc to 1.65.0

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/user.rs
- cli/src/commands/update/mod.rs
- cli/src/commands/update/users.rs
For https://reinfer.atlassian.net/browse/RE-2862
Adds a bulk update for user objects.
Example usage: update all users who have the `alerts-write` or `alerts-read` permissions in any project, to not have them.
```bash
cargo run -- -o json get users > users.jsonl
cat users.jsonl | jq -rc '. as $user | .organisation_permissions | map_values(select(any(. == "alerts-write" or . == "alerts-read")) | map(select(. != "alerts-write" and . != "alerts-read"))) | select(length > 0) | {"id": $user.id, "organisation_permissions": . }' > updated_users.jsonl
bat updated_users.jsonl
cargo run -- update users -f updated_users.jsonl
```
Tested against local data.
> api/cli: add update users command (RE-2862)

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/comment.rs
- api/src/resources/dataset.rs
- cli/src/commands/get/comments.rs
- cli/src/commands/update/users.rs
In order to be able to do an analysis like "X user property by label", I need to know a specific auto-threshold for each predicted label. The idea in this PR is that if a `--model-version` flag is provided to `re get comments --predictions true`, instead of fetching the latest predictions the CLI will fetch predictions from the specified model version with the corresponding auto-threshold information (using the [predict-comments](https://developers.reinfer.io/api/reference/predictions#get-predictions-for-a-pinned-model-by-comment-id) v1 route).
The output is not roundtrippable---I think that's fine? But happy to change if there are better ideas.
> comments: support fetching auto-thresholded labels

- CHANGELOG.md
- api/src/error.rs
- api/src/lib.rs
The `join` function only joins to the base of a given `url`, this is incompatible with deployments which live in sub directories. This PR seeks to address that.
> api: remove semantic-url-joins

- CHANGELOG.md
- Cargo.lock
- api/Cargo.toml
- api/src/error.rs
- api/src/lib.rs
- api/src/resources/mod.rs
- api/src/resources/quota.rs
- api/src/resources/tenant_id.rs
- cli/src/commands/create/mod.rs
- cli/src/commands/create/quota.rs
Add a new `create quota` command, to allow support users to set values for quotas for specific resources.
Example usage:
```bash
re create quota --reinfer-tenant-id abcdefabcdefabcd --quota-kind labels_per_dataset --limit 50
```
> Add `create quota` command

- CHANGELOG.md
- Cargo.lock
- README.md
- api/Cargo.toml
- cli/Cargo.toml
v0.12.3 -> v0.13.0 as we're adding a new feature
we've been treating patch versions as minor versions in the past but I think it's good to follow semantic versioning conventions! (unless I'm confused about them)
> release v0.13.0

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/comment.rs
- api/src/resources/dataset.rs
- api/src/resources/statistics.rs
- cli/src/commands/get/comments.rs
Expands the scope of queries that can be made to the statistics endpoint. Needed for an internal project.
> api: add time series and by label filters to statistics

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/comment.rs
- api/src/resources/dataset.rs
Adds the dataset `query` endpoint to the api client. Needed for an internal project.
> api: add query endpoint

- api/src/resources/dataset.rs
Continuation should be skipped on `None` value
> api: skip continuation on none

- api/src/resources/comment.rs
- api/src/resources/dataset.rs
Allows users to filter on user properties when making query requests
> api: add user properties filters to query request

- cli/src/commands/mod.rs
Remove erroneous `"` from no charge prompt
> remove double quote from charge warning message

- CHANGELOG.md
- api/src/retry.rs
- cli/src/main.rs
Retry requests when there is a connection issues. Helps prevent long running jobs from failing during deployments.
> cli: retry requests when there is a connection issue

- CHANGELOG.md
- api/src/retry.rs
> cli: retry too many request responses

- CHANGELOG.md
- api/src/retry.rs
So we retry request errors caused by deployments
> cli: retry on request errors

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/dataset.rs
- cli/src/commands/get/comments.rs
Adds ability to filter on user properties when getting comments, currently only supports string properties with `any_of` filter
> cli: add ability to filter on user properties when getting comments

- api/src/resources/bucket.rs
- cli/src/printer.rs
It is my understanding that none of the [update-related timestamps on bucket](https://github.com/reinfer/platform/blob/master/store/reinfer/store/bucket/resources.py#L79-L83) are currently being updated (following transition from bucket states to folder states), and we don't have a "most recent folder state update timestamp" field either, so this PR removes the "Updated" column from the CLI's bucket output, as it is now wrong.
> cli: do not print bucket updated timestamp

- CHANGELOG.md
- api/src/lib.rs
- cli/src/commands/get/sources.rs
- cli/src/printer.rs
- cli/tests/test_comments.rs
Optionally print `num_comments` when getting sources
> commands: add source statistics to table output

- CHANGELOG.md
- api/src/error.rs
- api/src/lib.rs
- api/src/resources/comment.rs
- api/src/resources/stream.rs
- cli/src/commands/create/mod.rs
- cli/src/commands/create/streams.rs
- cli/src/commands/get/streams.rs
Adds ability to round trip streams
> streams: add ability to create streams

- CHANGELOG.md
- Cargo.lock
- api/Cargo.toml
Relevant to other version upgrade/standardisation work in `platform`
>  chore: upgrade ordered-float to 3.9.1

- CHANGELOG.md
- api/src/resources/user.rs
- cli/src/printer.rs
Show's user's global permissions when getting users
> commands: show globabl permissions when getting users

- CHANGELOG.md
- api/src/resources/dataset.rs
- cli/src/commands/get/datasets.rs
- cli/src/printer.rs
- cli/tests/common.rs
- cli/tests/test_datasets.rs
Adds flag to get stats for datasets
> commands: add get dataset stats

- CHANGELOG.md
- cli/src/commands/get/users.rs
- cli/tests/test_datasets.rs
Allows you to filter `get users` by a project and permissions
> commands: filter get users by project and permissions

- cli/publish-binaries
Seems like the default name changed, making it explicit to get around this.
> publish: explicit name for deb package

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/stream.rs
Fixes the url we use for fetching streams and also makes sure we return an additional url we're adding to the fetch response
> fix(api): update fetch stream url

- CHANGELOG.md
- cli/src/commands/create/bucket.rs
Makes the transform tag optional when creating buckets and defaults to the same tag as the platform
> feat(commands): transform tag optional on create bucket

- CHANGELOG.md
- Cargo.lock
- api/src/lib.rs
- api/src/resources/mod.rs
- api/src/resources/stream.rs
- api/src/resources/validation.rs
- cli/Cargo.toml
- cli/src/commands/create/streams.rs
- cli/src/commands/get/mod.rs
- cli/src/commands/get/streams.rs
- cli/src/main.rs
Adds a `get stream-stats` command. The objective of which is to make it easier to understand the impact of upgrading a model version without changing thresholds. The command lets you;
- Get Stream Validation Stats on their own
- Get Stream Validation Stats and compare those stats to a specified model version / dataset and prints a comparison in precision and recall at the same thresholds
> feat(stream-stats): add command for displaying stream validation stats

- cli/src/commands/get/streams.rs
Adds some additional data for the stream stats. Namely;
- What precision would you expect if the recall was the same. What threshold do you need for that?
- What precision would you expect if the precision was the same. What threshold do you need for that?
> add more stream label validation stats

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/audit.rs
- api/src/resources/mod.rs
- api/src/resources/tenant_id.rs
- cli/src/commands/get/audit_events.rs
- cli/src/commands/get/mod.rs
- cli/src/printer.rs
Adds a command to return audit events
> commands: add get audit events command

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/comment.rs
- cli/src/commands/get/comments.rs
> fix(api): fix fetch & advance stream requests

- CHANGELOG.md
- api/src/resources/comment.rs
- cli/src/commands/get/comments.rs
Fixes this mistake: https://github.com/reinfer/cli/commit/f2edc087acaea57afb4b89c28e9e07b3670a9003
> fix(labelling): Fix label prediction type

- CHANGELOG.md
- api/src/resources/quota.rs
- cli/src/commands/create/quota.rs
Add support for setting `auto-increase-up-to` in quotas.
If the `--auto-increase-up-to` flag is passed to `re create quotas`, then the value will be set in the database for the relevant tenant.
Otherwise, it will just not be changed.
> Add support for setting 'auto-increase-up-to' in quotas

- CHANGELOG.md
- cli/src/commands/config.rs
- cli/src/config.rs
- cli/src/main.rs
Makes the `re -c <context>` required if you're a UiPath user / if you opt for that in the config
> feat(cli): add feature to make context a required field

- CHANGELOG.md
- api/src/resources/dataset.rs
- cli/src/commands/get/comments.rs
Allows users to filter on attachment types when running `get comments`
> feat(commands): filter get comments on attachment type

- api/src/resources/bucket_statistics.rs
- cli/src/commands/get/emails.rs
- cli/src/printer.rs
The bucket count is now returned as either an exact count or as a lower bound to avoid expensive aggregations for buckets containing more than 100K emails.
> fix(stats): update api schema for bucket statistics

- CHANGELOG.md
- cli/src/commands/create/annotations.rs
- cli/src/commands/create/comments.rs
- cli/src/main.rs
Adding a flag to attempt to resume processing when operations fail. Starting with annotations but could later be used for comments also
> feat(commands): add lossy flag when creating annotations

- CHANGELOG.md
- api/src/lib.rs
- api/src/resources/comment.rs
- api/src/resources/email.rs
- cli/src/commands/create/comments.rs
- cli/src/commands/create/emails.rs
- cli/src/commands/parse/mod.rs
Adds a `--resume-on-error` flag for uploading comments and emails. When the api returns an error the CLI will split a particular batch into individual requests, attempt each one individually and skip any individual request that fail
> feat(commands): add resume on error for comments and emails

- CHANGELOG.md
- api/src/resources/comment.rs
Defaulting to empty vec if not present so backups impacted by this won't be broken
> fix(api): Always serialize assigned

- CHANGELOG.md
- api/src/lib.rs
May result on 409 on retry if the put actually worked, but adding anyway as (anecdotally) most of the time the connection doesn't make it to us
> chore(api): retry put comments requests

- CHANGELOG.md
- Cargo.lock
- api/src/resources/dataset.rs
- cli/Cargo.toml
- cli/src/commands/get/comments.rs
Adds ability to randomly sample when getting comments (useful for sampling attachments)
> feat(cli): add ability to sample comments

- CHANGELOG.md
- cli/src/commands/config.rs
Changes the parse logic so we don't drop too much from the path
> fix(cli): config from url; don't strip entire path

- CHANGELOG.md
- Cargo.lock
- api/src/lib.rs
- api/src/resources/attachments.rs
- api/src/resources/comment.rs
- api/src/resources/dataset.rs
- api/src/resources/label_def.rs
- api/src/resources/source.rs
- cli/Cargo.toml
- cli/src/args.rs
- cli/src/commands/create/annotations.rs
- cli/src/commands/mod.rs
- cli/src/commands/package/download.rs
- cli/src/commands/package/mod.rs
- cli/src/commands/package/upload.rs
- cli/src/main.rs
- cli/tests/test_datasets.rs
Adds `re package download` and `re package upload` where a `package` is a zip containing all the dependencies for an ixp project (dataset def, source def, annotations, comments, documents etc...) allowing users to move around stuff with minimal fuss. 
One day I'll expand the scope of this to include CM projects.
> feat(commands): add package commands

- CHANGELOG.md
- api/src/resources/dataset.rs
- cli/src/commands/package/download.rs
Allows users to specify the project name when downloading packages for legacy ixp projects
> feat(cli): allow users to specify project name when downloading packages
